matplotlib/cheatsheets

cheatsheets.tex

Use 'center left' and 'center right' for backwards compatibility.
Correct x value for D case.

Fix issue #24 legend placement

---

handout-tips.tex

No need for a list comprehension; just call `cmap(list)`.
Also, use `Oranges` colormap instead of `Blues` because the illustrative image is in orange and using `Blues` is slightly confusing then.

cmap() can be called on array-like

---

cheatsheets.tex

When calling `scatter`, the correct argument name for setting marker style is `marker` rather than `markers` (cf. [matplotlib.pyplot.scatter](https://matplotlib.org/3.2.0/api/_as_gen/matplotlib.pyplot.scatter.html)). 
This PR fixes this.

Fix scatter "marker" argument name

---

cheatsheets.tex
scripts/linestyles.py

I noticed a couple of the API links were wrong, so I've corrected them here. In the process I also:
- cleaned some trailing whitespaces
- standardized the fontspec defs in `cheatsheet.tex`
~~WIP because I'm still apparently failing to load all fonts correctly; the text in the "legend placement" section is messed up and is causing the whole thing to spill onto a third page.~~

Fix API links

---

handout-beginner.tex
handout-tips.tex

improve the consistency of whitespace between function arguments

normalize whitespace

---

.github/workflows/main.yaml
.gitignore
Makefile

This PR should create a new `gh-pages` branch with the latest cheatsheets. The `gh-pages` branch will not keep track of changes, rather, the cheatsheets will be replaced with each new commit to `master`. With GitHub Pages working properly, the PDFs and PNGs will be available at https://matplotlib.org/cheatsheets/cheatsheets.pdf, and so on.

add GitHub Pages site with the latest cheatsheets and handouts

---

handout-beginner.tex

Hello.
Thank you for making a great cheat sheet.
Perhaps there is a typo here?
I'm not familiar with Python.
I found PR(matplotlib#34). But it is not fixed here at that time. So maybe it's not a typo?
I tried it in Jupyter Lab, but the cheat sheet code doesn't seem to work.
Please check it.
Best regards.

Fix a typo

---

scripts/projections.py

The dataset that `cartopy` downloads comes from a CDN (http://naciscdn.org/) that goes down intermittently. The dataset is also hosted on S3, and this PR updates the download URL to point to the S3 source (cf. https://github.com/SciTools/cartopy/issues/1325#issuecomment-904343657).

update `cartopy` download URL

---

.bumpversion.cfg
Makefile
cheatsheets.tex

Fix the matplotlib logo in the cheatsheets according to the suggestion https://github.com/matplotlib/cheatsheets/pull/61#issuecomment-907870441 from @timhoffm.
If it is straightforward to make the Calibri font available on the GHA machine, then the script method for generating the logo could continue.

fix matplotlib logo

---

scripts/interpolations.py

Attempts to address #28.
- replace `'none'` with `blackman`
Something else to consider would be making the image data the same as what is used in the current matplotlib [gallery example](https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html) for the interpolation methods. To that effect, I could add a commit to this PR.

update selection of interpolation methods

---

docs/index.rst

Note that the "social" link at the top links to matplotlib's repo, not the cheatsheets.  Not sure if that should be fixed somehow - its kind of nice for this to look like it is part of Matplotlib and keep the top nav consistent. However, this seems good as a stopgap...

DOC: add link to github to page

---

cheatsheets.tex

- Use `color='green'` instead of `color='C1'` for Quick Start. 'C1' is too obscure and colorcycles too much of a concept for the Quick Start.
- Whitespace: Use PEP-8 whitespace rules in code snippets
- Remove [explode] from `pie()` and [cmap] from `imshow()`: All other functions only list the primary data fields (with the exception of `plot(..., [fmt])`, but that function is so prominent that I'll make an exception for it).
The parameters `cmap` and `explode` are still listed, so that information is not lost.

Formatting adjustments

---

scripts/advanced-plots.py
scripts/basic-plots.py

While not visible in the cheatsheet itself, we should still adhere to common best practices, to be a role model for potential contributors.

Apply PEP-8 compatible code formatting

---

cheatsheets.tex
scripts/anatomy.py
scripts/annotate.py

- annotation: missing x in xycoords and "text" instead of "Annotation"
to correspond to function call signature above
- clear a figure how-to: make code correspond to heading
- remove ticks how-to: same for yaxis as is the other how-to's
- explicitly set legend location in anatomy.py as mpl 3.5.0 "best"
default location results in lower right corner

Fix various typos and inconsistencies

---

README.md
fonts/Makefile

which is required in font.py.
Closes #99.
With the Pacifico font installed, the cheatsheet looks correctly:

Add missing font Pacifico

---

.bumpversion.cfg
Makefile
cheatsheets.tex
check-matplotlib-version.py
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
requirements/requirements.in
requirements/requirements.txt

Bump the version of matplotlib being used to generate the cheatsheets and handouts.
This is done with:
```shell
bumpversion minor && make requirements
```

bump matplotlib version

---

cheatsheets.tex
handout-tips.tex

- change non-existing method `ax.set_suptitle` to `fig.suptitle` and
combine `patch.set_alpha(0)` for `fig` and `ax` into one line to make
room for new line `fig.suptitle()`
- fix typo

Fix suptitle setting

---

handout-intermediate.tex

Simple fix
Proof
```
[weissmann@larissa ~]$ ipython
Python 3.9.9 (main, Nov 20 2021, 21:30:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import matplotlib.pyplot as plt
In [2]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
In [2]: plt.subplots((3,3))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-93a8c9ce4987> in <module>
----> 1 plt.subplots((3,3))
/usr/lib/python3.9/site-packages/matplotlib/pyplot.py in subplots(nrows, ncols, sharex, sharey, squeeze, subplot_kw, gridspec_kw, **fig_kw)
1433     """
1434     fig …
```

Simple fix

---

cheatsheets.tex
scripts/annotation-arrow-styles.py

- make room for two additional annotation arrow styles (so that `'wedge'` is show again)
- add possibility to set tick labels together with tick positions

Update for version 3.5.0

---

cheatsheets.tex

Using `ax.set_xticks(rotation=90)` without passing labels is discouraged by the documentation. It recommends `ax.tick_params(axis='x', rotation=90)` instead.
Closes #108.

Improve tick label rotation method

---

Makefile

Make the background of the png preview images of the pdf files opaque white instead of transparent.
Closes #110

Make png background opaque white

---

handout-beginner.tex

Hello, this is the pull request to resolve issue #117.
There is no need to put the parenthesis around the number of rows/cols of subplots. 
(It's my first pull request so I'm not sure whether I follow the common practice.)

Update the beginner tex file for the issue #117

---

cheatsheets.tex

Change the casing in two locations.
Although the casing corresponds to the section titles of the original paper, the cheat sheet does not even use title casing for its titles.
Inconsistent within the list, and with the argument of title case not even being used for titles, sentence case seems better.

Change casing of sentences

---

.circleci/config.yml
.github/workflows/main.yaml

The docker image is deprecated: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
Also updated action versions for GitHub.

Update docker and action versions

---

cheatsheets.tex

- the correct name of the projection is Orthographic instead of Cartographic.
- use standard import convention to make the line a bit shorter,
see https://scitools.org.uk/cartopy/docs/latest/matplotlib/intro.html.
- fix wrong API link for cartopy
- add missing (lost) API link for 3d
Also removed some commented lines from previous changes, as I think the history should be better looked up in version control than in the code itself.

Fix non-existent cartopy projection

---

scripts/tip-transparency.py

It will now always produce:
instead of a different image each time.

Add a randomness seed to transparency script

---

cheatsheets.tex
handout-beginner.tex

Some examples call `fig.show()` with the expectation that a matpltolib figure will be displayed on-screen. However, since `fig.show` does not manage the backed GUI mainloop this will seemingly fail. In most cases, it will be more convenient for end-users to rely on `plt.show` to display figures.
Resolves #134

Replace calls to fig.show() with plt.show()

---

.github/workflows/main.yaml

The older one was giving deprecation warnings at the end of a build.

Bump pre-commit action version

---

.github/workflows/main.yaml
Makefile
check-diffs.py

Unfortunately, from what I've read, you can't upload an image from Actions, so you still need to download the build artifact to see the diff, but it's one less step to do yourself manually.

Add image diffs against previous build to CI results

---

requirements/requirements.in
requirements/requirements.txt

Fixes https://github.com/matplotlib/cheatsheets/issues/124.

Bump cartopy version

---

.bumpversion.cfg
Makefile
cheatsheets.tex
check-matplotlib-version.py
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
requirements/requirements.in
requirements/requirements.txt

I figure it might be easier doing the Matplotlib version bumps one meso version at a time, to make PRs easier to review, and to make any changes to the cheatsheets easier to understand/debug/fix.

Bump Matplotlib to 3.6

---

.bumpversion.cfg
Makefile
cheatsheets.tex
check-matplotlib-version.py
docs/conf.py
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
requirements/requirements.in
requirements/requirements.txt

And also Cartopy to latest version to make it installable on current versions of Python.
Fixes #116 
Fixes #124

Bump to Matplotlib 3.7.1

---

cheatsheets.tex
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
scripts/sine.py

Add spaces where possible. Fix `sine*` plots examples to match code and text. Fix Performance tip which didn't run.

Fix minor typos

---

.github/workflows/main.yaml
requirements/requirements.in
requirements/requirements.txt

A locally-compiled shapely was necessary for older Cartopy that compiled against the same libraries, but it's no longer doing that, so we can use binary Shapely again.

Allow binary shapely wheels

---

docs/conf.py
docs/index.rst
requirements/requirements.in
requirements/requirements.txt

This updates the sphinx theme versions to match the ones currently used by `matplotlib`. This should bring the appearance of https://matplotlib.org/cheatsheets/ into line with https://matplotlib.org/ and the main docs site.
Note that this deliberately downgrades `pydata-sphinx-theme` because of https://github.com/matplotlib/mpl-sphinx-theme/issues/80. The new pin is `0.13.3`, which is what the main Matplotlib docs currently use.

Bump version of Matplotlib sphinx theme

---

Makefile
check-links.py
scripts/colormaps.py
scripts/colors.py

All the special cases other than Greys are just the size of the colormap themselves. Also, colormaps are at most 256 elements long, so using `n=512` is probably not necessary.
Also, use the same algorithm as the [Specifying colors tutorial](https://matplotlib.org/stable/users/explain/colors/colors.html#comparison-between-x11-css4-and-xkcd-colors) to choose text colour over colour cycles.

Simplify colormap plotting

---

fonts/Makefile

For some reason downloading the `.zip` from google fonts no longer works (I can reproduce the same error locally on my laptop). Instead, get it from the source repository of the font.

Fix downloading pacifico font

---

.bumpversion.cfg
Makefile
cheatsheets.tex
check-matplotlib-version.py
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
requirements/requirements.in
requirements/requirements.txt
scripts/markers.py

Updates:
- The `make logos` target isn't needed, because there's a copy of the logo already in this repository
- The second line of markers needed it's color setting correctly to show up now in 3.8
Otherwise I've checked the diffs and everything looks fine.
Note that this isn't the most recent release of 3.8 (3.8.4), but 3.8.2, the version that was out when I originally wrote this PR. I think we should just run with this, and I can do a follow up PR soon after to update to 3.9, and then 3.10. Doing it in stages across PRs seems to be the best thing to do to me, instead of trying to do a big jump in one go.

Update Matplotlib version to 3.8

---

.github/workflows/main.yaml
.pre-commit-config.yaml

Apply recommended hardening steps including:
- pinning to a SHA any actions used
- not persisting the read token on checkout
- setting the default permissions
- adding a depandabot file for GHA

CI: Harden GHA configuration

---

.github/workflows/main.yaml

This should fix https://github.com/matplotlib/cheatsheets/issues/167 - I'm not sure there's any way to tell without merging.

Fix cheatsheet publishing

---

.bumpversion.cfg
cheatsheets.tex
check-matplotlib-version.py
handout-beginner.tex
handout-intermediate.tex
handout-tips.tex
requirements/requirements.in
requirements/requirements.txt

I've checked the diffs manually, and they look fine. Lots of minor changes to text layout, and everything else is unchanged.

Update Matplotlib version to 3.9
